development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: techradar_development
  pool:     5
  username: postgres
  password: password
  template: template0 # seems needed for c9.io, not entirely sure why

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: techradar_test
  pool:     5
  username: postgres
  password: password
  template: template0 # seems needed for c9.io, not entirely sure why
